### PR TITLE
Object manipulation 3

### PR DESCRIPTION
**Pull request by joseph-w-valdez**
https://user-images.githubusercontent.com/117682160/209454620-267db61c-bff4-4a50-8436-41c1dc31909e.mp4

### CODE REVIEW

**Comment by joseph-w-valdez** [comment]
https://i.imgur.com/Hg5vKXG.png

**Comment by joseph-w-valdez** [comment]
image

**Comment by joseph-w-valdez** [comment]
image

**Comment by joseph-w-valdez** [comment]
image

**Comment by joseph-w-valdez** [comment]
Also completed the optional objective of rerunning the game with just members involved in winning tiebreakers.

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
